image: symfony2

build:
  - composer install --ansi --no-progress --no-dev --no-interaction --prefer-dist
  - php setup.php

writable:
    - app/logs
    - app/cache

    - web/images
    - web/cars
    - web/bikes
