admingenerator_generator:
    use_propel:          true
    use_doctrine_orm:    true

    overwrite_if_exists: %kernel.debug%

    base_admin_template: AdmingeneratorGeneratorBundle::base_admin.html.twig
