vich_uploader:
    db_driver: propel

    mappings:
        car_front_mapping:
            uri_prefix:         /cars/front
            upload_destination: %kernel.root_dir%/../web/cars/front
        car_back_mapping:
            uri_prefix:         /cars/back
            upload_destination: %kernel.root_dir%/../web/cars/back

        image_mapping:
            uri_prefix:         /images
            upload_destination: %kernel.root_dir%/../web/images
