KPhoenMultipleUploadableBundle_admin_k_phoen_multiple_uploadable_bundle_Bike:
    resource: "@KPhoenMultipleUploadableBundle/Controller/Bike/"
    type:     admingenerator
    prefix:   /admin/bike

KPhoenMultipleUploadableBundle_admin_k_phoen_multiple_uploadable_bundle_Car:
    resource: "@KPhoenMultipleUploadableBundle/Controller/Car/"
    type:     admingenerator
    prefix:   /admin/car

KPhoenSingleUploadableBundle_admin_k_phoen_single_uploadable_bundle_Image:
    resource: "@KPhoenSingleUploadableBundle/Controller/Image/"
    type:     admingenerator
    prefix:   /admin/image

