services:
    multiple_uploadable.admin.car:
        class: KPhoen\Bundle\MultipleUploadableBundle\Admin\CarAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Multiple Uploadable Field", label: "Car" }
        arguments:
            - ~
            - KPhoen\Bundle\MultipleUploadableBundle\Entity\Car
            - ~

    multiple_uploadable.admin.bike:
        class: KPhoen\Bundle\MultipleUploadableBundle\Admin\BikeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Multiple Uploadable Field", label: "Bike" }
        arguments:
            - ~
            - KPhoen\Bundle\MultipleUploadableBundle\Entity\Bike
            - ~
